"""The report. Every number here was measured, predicted by the saved model, or taken
from the controlled test -- and the report says which.

No sentence in this file is generated by a model, and the one place model text could
reach the page (the recommendations) has already passed the ethics filter.
"""

from __future__ import annotations

from .advise import DIAGNOSES, limits
from .state import AdvisorState

DIAGNOSIS_NOTE = {
    "absent": (
        "Sorun görünürlükten önce **bulunabilirlik**: asistanın önüne gelen sonuçlarda "
        "yoksun, dolayısıyla cevapta da yoksun. Kontrollü testte bu adımı atmak "
        "anılmayı %2'den %33'e çıkardı; en büyük tek kazanç burada."
    ),
    "low_rank": (
        "Getirilen sonuçlarda varsın ama aşağıdasın. Kontrollü testte aynı sayfanın "
        "5. sıradan 1. sıraya çıkması anılmayı %33'ten %65'e taşıdı."
    ),
    "ceiling": (
        "Anılıyorsun, yani içerik tarafı çalışıyor. Ama hiçbir yanıtta ilk sırada "
        "değilsin ve kontrollü testte hiçbir müdahale bunu değiştirmedi. Bu bir içerik "
        "sorunu değil, marka tanınırlığı sorunudur."
    ),
    "leader": (
        "Bu sorgularda zaten öndesin. Buradaki iş kazanmak değil, konumu korumak: "
        "rakiplerinin girdiği listelerde kalmaya devam et."
    ),
    "thin": "Ölçüm yeterli gözlem üretmedi; sonuçlar yorumlanmamalıdır.",
}


def pct(value: float | None) -> str:
    return "–" if value is None else f"%{100 * value:.0f}"


def _signal_section(state: AdvisorState) -> list[str]:
    scores = state.get("scores") or {}
    if not scores:
        return []
    brand = state["brand"]
    curated = state.get("curated", True)
    origin = (
        "Bu sektör modelin eğitim verisinde var."
        if curated
        else "Bu sektör modelin eğitim verisinde **yok**; skor, beş sektörde öğrenilen ve "
        "hiç görmediği sektörlerde doğrulanan göreli sinyallerden taşındı."
    )
    lines = [
        "## Öğrenilmiş sinyal: rakiplerine göre konumun",
        "",
        "Kayıtlı yanıtlardan öğrenilen model (M2-Invariant) marka kimliğine ve sektöre "
        "bakmaz; yalnız aynı arama sonuçlarında rakiplerine göre nerede durduğuna bakar. " + origin,
        "",
        f"| | {brand} | Karşılaştırılan rakipler |",
        "|---|---:|---:|",
        f"| Anılma olasılığı (tahmin) | {pct(scores.get('score_mention'))} | "
        f"{pct(scores.get('rival_score_mention'))} |",
        f"| Birincil öneri olasılığı (tahmin) | {pct(scores.get('score_top'))} | "
        f"{pct(scores.get('rival_score_top'))} |",
        "",
        f"{scores.get('candidates', 0)} aday marka içinde anılma tahmininde "
        f"**{scores.get('rank', '–')}.** sıradasın. Karşılaştırılan rakipler: "
        f"{', '.join(scores.get('compared_with') or []) or '–'}.",
        "",
    ]
    rows = state.get("signals") or []
    if rows:
        lines += [
            "| Sektörler arasında taşınan sinyal | Sen | Rakipler | Durum |",
            "|---|---:|---:|---|",
        ]
        for row in rows:
            status = "**geride**" if row["lagging"] else "–"
            lines.append(
                f"| {row['label']} | {row['brand']:.2f} | {row['rivals']:.2f} | {status} |"
            )
        lines.append("")
    return lines


def report(state: AdvisorState) -> str:
    brand = state["brand"]
    m = state.get("measures", {})
    diagnosis = state.get("diagnosis", "thin")
    lines = [
        f"# {brand}: canlı görünürlük teşhisi",
        "",
        f"Sektör: {state['sector']} · Dil: {state['language']} · "
        f"{m.get('queries', 0)} sorgu, {m.get('n_observations', 0)} asistan yanıtı "
        "(Gemini 3.5 Flash Lite)",
        "",
        f"## Teşhis: {DIAGNOSES.get(diagnosis, diagnosis)}",
        "",
        DIAGNOSIS_NOTE.get(diagnosis, ""),
        "",
        "## Ölçülen görünürlük",
        "",
        "| Ölçü | Değer |",
        "|---|---:|",
        f"| Arama kapalıyken anılma (tanınırlık) | {pct(m.get('mention_off', 0))} |",
        f"| Arama açıkken anılma | {pct(m.get('mention_on', 0))} |",
        f"| İlk anılan marka olma | {pct(m.get('first_on', 0))} |",
        f"| Arama sonuçlarında görünme | {pct(m.get('retrieval_presence', 0))} |",
        f"| Göründüğünde ortanca sıra | {m.get('best_position_median') or '–'} |",
        f"| Kaç sorguda görünüyorsun | {m.get('queries_with_presence', 0)}/{m.get('queries', 0)} |",
        "",
    ]
    rivals = state.get("rivals") or []
    if rivals:
        lines += [f"Senin yerine en çok anılan markalar: {', '.join(rivals)}.", ""]
    lines += _signal_section(state)

    lines += ["## Ne yapmalı?", ""]
    for index, rec in enumerate(state.get("recommendations", []), 1):
        lines += [
            f"### {index}. {rec['title']}",
            "",
            rec["why"],
            "",
            f"**Yapılacak:** {rec['action']}",
            "",
            f"*{rec['verdict']}*",
            "",
        ]
        if rec.get("targets"):
            lines += [
                "| Alan adı | Andığı rakipler | Sıra | Sayfa |",
                "|---|---|---:|---|",
            ]
            for target in rec["targets"]:
                lines.append(
                    f"| {target['domain']} | {', '.join(target['rivals'])} | "
                    f"{target.get('position') or '–'} | {target['link']} |"
                )
            lines.append("")

    names = state.get("candidates") or []
    if names:
        lines += [
            "## Karşılaştırılan markalar",
            "",
            f"{len(names)} marka: {', '.join(names)}.",
            "",
            "Liste arama sonuçlarından çıkarıldı. Eksik ya da yanlış ad varsa "
            "`--add-rival` / `--drop-rival` ile düzeltip yeniden çalıştırın; önbellekteki "
            "çağrılar yeniden ücretlendirilmez.",
            "",
        ]

    lines += ["## Bu rapor ne söylemiyor", ""]
    lines += [
        f"- {item}"
        for item in limits(state["sector"], state["language"], state.get("curated", True))
    ]
    lines += ["", "## Koşu notları", ""]
    lines += [f"- {note}" for note in state.get("notes", [])]
    lines += [
        "",
        "Ölçülen etkiler `reports/intervention/` altındaki kontrollü testten gelir; "
        "bu koşuda yeniden ölçülmemiştir.",
    ]
    return "\n".join(lines) + "\n"
